#en-tête
swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

#chemins et endpoints
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API endpoint for user authentication.
      parameters:
        - in: body
          name: body
          description: Credentials needed for logging in.
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successful, returns token.
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid credentials provided.
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Fetch User Profile
      description: API for fetching a user's profile using a Bearer Token.
      responses:
        '200':
          description: Profile retrieval successful.
          schema:
            $ref: '#/definitions/UserProfile'
        '401':
          description: Unauthorized access.
        '500':
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update User Profile
      description: API for updating a user's profile using a Bearer Token.
      parameters:
        - in: body
          name: body
          description: Data to update in the user profile.
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      responses:
        '200':
          description: Profile update successful.
        '400':
          description: Invalid request format.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal Server Error

#Sécurité
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

#Définitions
definitions:
  User:
    type: object
    properties:
      email:
        type: string
        example: user@example.com
      password:
        type: string
        example: "StrongP@ssw0rd"
      firstName:
        type: string
      lastName:
        type: string
      userName:
        type: string

  Login:
    type: object
    properties:
      email:
        type: string
        example: user@example.com
      password:
        type: string
        example: "user_password"

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

  UserProfile:
    type: object
    properties:
      email:
        type: string
        example: user@example.com
      firstName:
        type: string
      lastName:
        type: string
      userName:
        type: string
